sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.ts
sonar.exclusions=dist/**,**/*.map
sonar.cpd.exclusions=src/commands/test-autogen.ts,__tests__/test-autogen-command.test.ts
