sonar.projectKey=Forge-Space_forge-ai-action
sonar.organization=forge-space
sonar.projectName=forge-ai-action

sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=dist/**,**/*.map,**/node_modules/**,**/coverage/**
sonar.coverage.exclusions=
sonar.cpd.exclusions=src/commands/test-autogen.ts,__tests__/test-autogen-command.test.ts
